### ISSUE TITLE
Running `cargo miri test` in a github action hangs with no output

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/miri#1345]
Example job:
```yaml
  test_miri:
    name: Test (Miri)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: miri
      - uses: actions-rs/cargo@v1
        with:
          command: miri
          args: test
```
