### ISSUE TITLE
Set MIRIFLAGS from .cargo/config.toml

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/miri#2347]
You can pass flags to rustc with [`build.rustflags`](https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags), and to rustdoc with [`build.rustdocflags`](https://doc.rust-lang.org/cargo/reference/config.html#buildrustdocflags).

```toml
[build]
rustflags = ["-C", "target-cpu=native"]
```

Supporting MIRIFLAGS the same way would be nice. Most of the time I want to run _every_ miri invocation for a project with a particular flag like `-Zmiri-disable-isolation`, so just setting it globally for the workspace would be ideal.

```toml
[miri]
miriflags = ["-Zmiri-disable-isolation"]
```

Related issue for MIRIFLAGS as command line arguments: https://github.com/rust-lang/miri/issues/2051
